from collections import deque
queue = deque(["Simple ","Anushka","Prerna "])
if len(queue)==0:
    print("Empty")
else:
    print("Nopn Empty")
queue.append("Himanshu")
queue.append("Ankur")
queue.append("Sanika")
queue.append("Gaytri")
queue.append("Samarth")
queue.append("Sambhav")
queue.append("Ayush")
print(len(queue))
queue.pop()
queue.pop()
queue.pop()
queue.pop()
print(queue)
queue.append("10")
queue.append("20")
print(queue)
queue.clear()
print(queue)
